### ISSUE TITLE
Attachments in imap2thehive

### ISSUE THREAD

**Issue by 0xtf** [xme/dockers#1]
First of all, thank you very much for the work done in this project! Code runs very well and is extremely helpful. The configuration file makes it a perfect combination for when TH supports multi-tenant/organizations.

I did notice that e-mails with attachments output the following INGO:

./imap2thehive.py -c imap2thehive.conf 
[INFO] Found attachment: CgbCdgVUIAAev9U.jpg-large.jpeg

Does IMAP2TheHive support adding files as observables? If not, is it feasible to think about doing so?

Thank you very much!

**Comment by xme** [comment]
Yes, it will. It has been implemented and I'll push the code today or tomorrow. Be patient :)

**Comment by 0xtf** [comment]
That's great Xavier! Thank you for the feedback.
