### ISSUE TITLE
xlsxtract.py

### ISSUE THREAD

**Issue by shuntera** [xme/dockers#10]
Where is this supposed to be placed?  It doesn't appear to be a part of the build so does it get put in the same directory as the Dockerfile, or in the data directory?  When I run the docker run command I just get told there is no urls.txt file, it does not attempt to parse the .xlsx file I placed there at all

**Comment by xme** [comment]
Create a mapping between your local directory (on the host) and /data
XLS files have to be placed into /data

**Comment by shuntera** [comment]
Yes I have the /data directory correctly mapped as that is where I have been placing the urls.txt file after i manually extract the URLs from the Excel file.  I also put the Excel files in that directory but they are not being parsed.  I think it may be a python path issue to do with openpyxl - but as I don't see any errors when running I can't say for sure.
