### ISSUE TITLE
"Cannot read imap2thehive.whitelists" from Cron Task

### ISSUE THREAD

**Issue by arnydo** [xme/dockers#17]
Hello,

Working on using Docker Compose to launch two containers, one imap2thehive and the other Davmail as a proxy to Exchange since we do not offer direct IMAP access. This is working as expected.

The issue is when the cron task is running for imap2thehive I am getting ```[ERROR]: Cannot read imap2thehive.whitelists: No such file or directory```.

I have take the same command from crontab and ran manually with success.

Is there any reason that this would behave any differently?

The imap2thehive.whitelists file is in the /opt/ dir.

Thank you

**Comment by xme** [comment]
Are you sure that the path is defined properly in imap2thehive.conf?

**Comment by arnydo** [comment]
I assumed the path was relative to the executable so I left it at the default (which worked when running manually). Set to the full path and it works as expected.

Thank you!

**Comment by SantiagoSerrao** [comment]
Hi! if you are trying to configure the cron and get this error  you need to configure the complete path in the file  imap2thehive.conf
