### ISSUE TITLE
imap2thehive FR - Case Template and Delete Email

### ISSUE THREAD

**Issue by 0xtf** [xme/dockers#2]
Hi,

As a follow up to the Twitter conversation:

The possibility of assigning cases created by imap2thehive to an existing Case Template would be really useful. 

Also, since most mailboxes will be used as intake for TheHive only, if there was the option to mark processed messages as deleted and after that expunged, that would be very interesting as well, since it would maintain the mailboxes clean/empty automatically. 

I'd be happy to test any of these features if needed. 

Thank you for your work!

**Comment by xme** [comment]
'Delete email' feature added!

**Comment by xme** [comment]
Added support to assign an existing template to created cases. 
Just test and report any issue / idea.
