### ISSUE TITLE
Only able to create cases, not alerts

### ISSUE THREAD

**Issue by iamgrimm** [xme/dockers#23]
I left all fields under [case] blank in the conf file (except tlp that threw an error) to try to force it to create an alert instead of a case, but it still creates a case.  What do I need to do to create an alert instead of a case, I don't see it in the documentation, but it seems to be possible based on the configuration file.

**Comment by SantiagoSerrao** [comment]
Hi!! i am having the same issue but i only can to create alerts intead of case
[alert]
tlp: 3
tags: email
keywords:
i only left without none config the keywords!
You can create case?

**Comment by iamgrimm** [comment]
> Hi!! i am having the same issue but i only can to create alerts intead of case
> [alert]
> tlp: 3
> tags: email
> keywords:
> i only left without none config the keywords!
> You can create case?

Yes, but I prefer cases.  Can you paste your imap2thehive.conf file so I can compare?  I am using the below.  My emails all have [Alert] in the title (not sure if case match is necessary?).  I would get errors if I did not put a tlp in the alert section, so I think that my issue might be in that the case section is not completely blank, so it creates a case.  Below is my conf file, what does yours look like when it creates alerts?
```
[imap]
host: outlook.office365.com
port: 993
user: <email address>
password: <mypassword>
folder: Inbox
expunge: true
spam: (X-Spam-Flag: YES)

[thehive]
url: http://127.0.0.1:9000
apikey: <my api key>
observables: true
whitelists:

[alert]
tlp: 3
tags: email
keywords: \S*(ALERT|VTMIS)\S*

[case]
tlp: 3
tags: email
tasks:
template:
files:

[custom_observables]
ossec_asset: Received From: \((\w+)\)\s
ossec_level: Rule: \w+ fired \(level (\d+)\)\s-
ossec_message: Rule: \w+ fired \(level \d+\)\s-> "(.*)"
ossec_rule: Rule: (\d+) fired \(level

[loggers]
keys=root,imap2thehive

[handlers]
keys=console,file

[formatters]
keys=simple,console

[logger_root]
level=INFO
handlers=console

[logger_imap2thehive]
level=DEBUG
handlers=file
propagate=1
qualname=imap2thehive

[handler_console]
class=StreamHandler
formatter=console
level=DEBUG
args=(sys.stdout,)

[handler_file]
class=FileHandler
level=WARNING
formatter=simple
args=('/var/log/imap2thehive.log', 'w')

[formatter_simple]
format=%(asctime)s %(levelname)s %(message)s

[formatter_console]
format=[%(levelname)s]: %(message)s
```

**Comment by SantiagoSerrao** [comment]
Hi!! 
Ok i resolve the creation of cases. 
My config file is : 
[case]
tlp: 3
tags: email
tasks: Investigation,Communication,Tracking
template:template
files:application/pdf/txt

[alert]
tlp:0 
tags:
Keywords:Alert

To create a case you need to create the template in the hive with the same name that you put in the conf file. 
Also i comment 
# Prepare the custom fields
        #customFields = CustomFieldHelper()\
         #   .add_string('from', fromField)\
          #  .add_string('attachment', str(attachments))\
           # .build()

that piece of code in the imap2thehive.py because i had an error when i run the script to read the emails.

**Comment by iamgrimm** [comment]
> Hi!!
> Ok i resolve the creation of cases.
> My config file is :
> [case]
> tlp: 3
> tags: email
> tasks: Investigation,Communication,Tracking
> template:template
> files:application/pdf/txt
> 
> [alert]
> tlp:0
> tags:
> Keywords:Alert
> 
> To create a case you need to create the template in the hive with the same name that you put in the conf file.
> Also i comment
> 
> # Prepare the custom fields
> ```
>     #customFields = CustomFieldHelper()\
>      #   .add_string('from', fromField)\
>       #  .add_string('attachment', str(attachments))\
>        # .build()
> ```
> 
> that piece of code in the imap2thehive.py because i had an error when i run the script to read the emails.

I am attempting to create an alert though not a case.  how was your config before when creating alerts?

**Comment by SantiagoSerrao** [comment]
I only change this: 
[alert]
tlp:3
tags:
Keywords:Alert

That is my config

**Comment by iamgrimm** [comment]
I realized I was matching ALERT but the subject contained Alert, so case matching turned out to be the issue.
