### ISSUE TITLE
Error when i executed

### ISSUE THREAD

**Issue by SantiagoSerrao** [xme/dockers#24]
Hi!!!
i am trying to use the script but when i run i have an error:
imaplib.error: command SEARCH illegal in state AUTH, only allowed in states SELECTED

how can i fix this??
Thanks!!

**Comment by denis-n-ko** [comment]
Hi,

it means you configured non existing folder

**Comment by SantiagoSerrao** [comment]
Thanks Denis! i alredy solve that and i am using the script so thanks again and thanks for share the script
