### ISSUE TITLE
Troubles accessing Office365

### ISSUE THREAD

**Issue by vi-or-die** [xme/dockers#4]
I am not sure how to approach this issue, however I hope that you may have some insight or experience to share. 

We are trying to integrate imap2thehive with a Office365 mailbox. From the beginning I have gotten the error message seen below. I know that IMAP is enabled for the mailbox, and this account doesn't have 2-factor. To make sure authentication is working I switched the host, user, and password to point to gmail and it worked successfully. I also validated that I can configure IMAP on the account and mailbox. This leads me to believe that I may not be properly configuring imap2thehive.

 Do you have any experience setting this up, or have any ideas on how to troubleshoot?
**Configuration**
```
[imap]
host: outlook.office365.com
port: 993
user: first.last@company.onmircrosoft.com
password: fakepw
folder: inbox
expunge: true
```
**Error Message**
```
$python imap2thehive.py -c imap2thehive.conf -v
[WARNING] Both case template and tasks are defined. Template (thehive_template) will be used.
[INFO] Processing first.last@company.onmircrosoft.com@outlook.office365.com:993/inbox
[ERROR] Cannot open incoming for first.last@trialtenant.onmircrosoft.com@outlook.office365.com: LOGIN failed.
```

**Comment by 0xtf** [comment]
You sure you wanted to put the password here?

**Comment by xme** [comment]
I hope it's a fake one or test account :)

**Comment by vi-or-die** [comment]
Thanks guys yes this was a trial account so no harm done. Super embarrassing none the less.

**Comment by xme** [comment]
I also get a "login failed" message with the credentials you posted but I hope they are not valid ones. I don't have a valid Office365 account to test. Can you provide me temporary credentials via a secure channel?

**Comment by 0xtf** [comment]
Just as a heads up ... When you have IMAP2TheHive working, with a service like O365, be prepared for the messages to be dropped if you send artefacts that are known malicious. Also, many of the file extensions are blocked (.pdf, .exe, etc) and will result in the e-mail not being processed.

**Comment by xme** [comment]
Did you test the credentials with another IMAP client? Does the code below works:
>>> import imaplib;
>>> M = imaplib.IMAP4_SSL('outlook.office365.com', 993)
>>> M.login('mylogin, 'myPassword')

**Comment by vi-or-die** [comment]
Tried the IMAP client referenced above and it seems to work. I changed the password to remove special characters. The % seemed to be the most disruptive with python.

>>> M = imaplib.IMAP4_SSL('imap.gmail.com',993)
>>> M.login('first.last@gmail.com', 'PasswO4rd')
('OK', ['first.last@gmail.com authenticated (Success)'])
>>> M = imaplib.IMAP4_SSL('outlook.office365.com',993)
>>> M.login('first.last@fakecompany.onmicrosoft.com', 'PasswO4d')
('OK', ['LOGIN completed.'])

When I tried to put the new password into the conf file still getting LOGIN failed. 

[WARNING] Both case template and tasks are defined. Template (thehive_template) will be used.
[INFO] Processing first.last@fakecompany.onmircrosoft.com@outlook.office365.com:993/inbox
[ERROR] Cannot open inbox for first.last@fakecompany.onmircrosoft.com@outlook.office365.com: LOGIN failed.


Testing account can be provided, just have to figure out the best way to do it.

**Comment by vi-or-die** [comment]
I think I have some good news... I modified the script to bypass the config file when handling the username and password for office 365. This was able to get the script to authenticate successfully to Office365. 


**OLD Configuration**
```
    try:
        typ,dat = mbox.login(config['imapUser'],config['imapPassword'])
    except:
        typ,dat = sys.exc_info()[:2]
```

**OLD Error**
```
[WARNING] Both case template and tasks are defined. Template (thehive_template) will be used.
[INFO] Processing first.last@company.onmircrosoft.com@outlook.office365.com:993/inbox
[ERROR] Cannot open inbox for first.last@company.onmircrosoft.com@outlook.office365.com: LOGIN failed.
```

**NEW Configuration**
```
 try:
        # New Change
        username = 'first.last@company.onmicrosoft.com'
        password = 'password'

        typ,dat = mbox.login(username, password)

        # typ,dat = mbox.login(config['imapUser'],config['imapPassword'])
    except:
```
**NEW Error**
```
[WARNING] Both case template and tasks are defined. Template (thehive_template) will be used.
[INFO] Processing first.last@company.onmircrosoft.com@outlook.office365.com:993/inbox
[INFO] Connected to IMAP server.
[INFO] 1 unread messages to process
Traceback (most recent call last):
  File "imap2thehive_v2.py", line 468, in <module>
    main()
  File "imap2thehive_v2.py", line 464, in main
    readMail(mailConnect())
  File "imap2thehive_v2.py", line 359, in readMail
    if submitTheHive(message) == True:
  File "imap2thehive_v2.py", line 200, in submitTheHive
    msg = email.message_from_bytes(message)
AttributeError: 'module' object has no attribute 'message_from_bytes'
```
I believe the Traceback error is a result of me not having TheHive authentication configured and not really having any emails in the mailbox. I also just found that there is another section where authentication to imap is present so I will be testing with that. That said I am going to be testing to see if there is an issue with the credentials being passed from the conf file to script and try to build some methods to fix that. 

**On another note...**
I also noticed a missing space between the username and password. I don't think this is explicetly required  `config['imapUser'],` and `config['imapPassword']` like this`config['imapUser'], config['imapPassword']` but this doesn't fix the error so may be irrelevant

**Comment by xme** [comment]
Thank you for your investigation. I'm currently abroad but I'll try to have a look asap at your comments.

**Comment by vi-or-die** [comment]
I think the issues being seen before may have been partially environmental. I was able to stand up a different mailbox and authentication works. However that said I am still seeing the issues demonstrated below. Each time I run the script the oldest message is marked as read but isn't imported into the Hive. 

Does the traceback error below give any information that would help guide me in a direction?

```
[INFO] Processing user@domain.com@outlook.office365.com:993/inbox
[INFO] Connected to IMAP server.
[INFO] 3 unread messages to process
Traceback (most recent call last):
  File "imap2thehive.py", line 481, in <module>
    main()
  File "imap2thehive.py", line 477, in main
    readMail(mailConnect())
  File "imap2thehive.py", line 372, in readMail
    if submitTheHive(message) == True:
  File "imap2thehive.py", line 194, in submitTheHive
    msg = email.message_from_bytes(message)
AttributeError: 'module' object has no attribute 'message_from_bytes'
```

**Comment by vi-or-die** [comment]
We figured out the issue to the problems. The wrong version of python was in use. Resolution was install Python, install pip 3 `sudo apt install python3-pip`, then re run the requirements installer `pip3 install -r requirements.txt`.


Thanks for the help, and sorry for the long rabbit trail for what ended up being two environmental issues. Great work on the script though.

**Comment by viszsec** [comment]
guys, any workaround to fix o365 from blocking the content of the email? cant see a word once pushed to thehive. only observables can be seen
